# CI的名称
name: Android CI

on:
  # 推送之后触发的jobs
  push:
    branches: [ "master" ]
  # 拉取之后触发的
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
         java-version: 1.8

    # - name: install gradlew
    #   run: gradle wrapper
     # 检查权限gradlew
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
      
    - name: Unit tests
      run: bash ./gradlew test --stacktrace
    
  #一个任务
  build:
    # 给任务定义一个名字
    name: Generate APK 
    # 指定当前任务运行的环境。比如上述示例中任务是在 ubuntu-latest 系统下运行。
    runs-on: ubuntu-latest

    steps:
    #指定当前任务的步骤列表。比如当前示例中，我们有多个任务，分别如下：
    
    # 检查JDK的版本
    - uses: actions/checkout@v3
    - name: set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: 1.8
        distribution: 'temurin'
        cache: gradle

    # 检查权限gradlew
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    # 执行gradleW build
    - name: Build with Gradle
      run: ./gradlew build
    # 执行构建 apk
    - name: Build APK
      run: bash ./gradlew :app:assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: App
        path: ${{ github.workspace }}/app/build/outputs/apk/debug/app-debug.apk
